name: Test Project 
#trigger 
on:
  test:
    runs-on: macos-12
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - naem: Install NodeJS
        uses: actions/setup-node@3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test 
        
